function throws() {
    // try {
    throw new Error("ERROR!!!!!")
    // } catch (e) {
    //     console.log(e)
    // }
}

// If the error is catched, the test will fail


module.exports = { throws }